// Custom icons export - from @heroicons/react v2
// Using ONLY verified icon names from the list
import { 
  HomeIcon,
  ClockIcon,
  PlayIcon,
  PlayCircleIcon,
  UsersIcon,
  ArrowTrendingUpIcon,
  ArrowTrendingDownIcon,
  CurrencyDollarIcon,
  CheckIcon,
  XMarkIcon,
  UserIcon,
  Cog6ToothIcon,
  Bars3Icon,
  ChevronRightIcon,
  ChevronDownIcon,
  StarIcon,
  HeartIcon,
  EnvelopeIcon,
  PhoneIcon,
  MapPinIcon,
  ExclamationCircleIcon,
  InformationCircleIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowPathIcon,
  MagnifyingGlassIcon,
  BellIcon,
  CalendarIcon,
  ClipboardDocumentListIcon,
  ClipboardDocumentCheckIcon,
  CreditCardIcon,
  WalletIcon,
  BanknotesIcon,
  GlobeAltIcon,
  ShieldCheckIcon,
  UserGroupIcon,
  ChartBarIcon,
  NoSymbolIcon,
  HandThumbUpIcon,
  HandThumbDownIcon,
  EyeIcon,
  EyeSlashIcon,
  LockClosedIcon,
  LockOpenIcon,
  KeyIcon,
  IdentificationIcon,
  DocumentTextIcon,
  FolderIcon,
  ArchiveIcon,
  TrashIcon,
  PencilIcon,
  PlusCircleIcon,
  MinusCircleIcon,
  XCircleIcon,
  CheckCircleIcon,
  CursorClickIcon,
  ExclamationTriangleIcon,
  ServerIcon,
  CloudUploadIcon,
  CloudDownloadIcon,
  CodeBracketIcon,
  TerminalIcon,
  CircleStackIcon,
  QuestionMarkCircleIcon,
  DocumentIcon,
} from '@heroicons/react/24/outline';

// Aliases
const TrendingUpIcon = ArrowTrendingUpIcon;
const TrendingDownIcon = ArrowTrendingDownIcon;
const DollarSignIcon = CurrencyDollarIcon;
const XIcon = XMarkIcon;
const MenuIcon = Bars3Icon;
const CogIcon = Cog6ToothIcon;
const MailIcon = EnvelopeIcon;
const HelpCircle = QuestionMarkCircleIcon;
const FileText = DocumentTextIcon;
const ThumbUpIcon = HandThumbUpIcon;
const ThumbDownIcon = HandThumbDownIcon;
const LocationMarkerIcon = MapPinIcon;
const RefreshIcon = ArrowPathIcon;
const SearchIcon = MagnifyingGlassIcon;
const ClipboardListIcon = ClipboardDocumentListIcon;
const ClipboardCheckIcon_check = ClipboardDocumentCheckIcon;

export {
  HomeIcon,
  ClockIcon,
  PlayIcon,
  PlayCircleIcon,
  UsersIcon,
  ArrowTrendingUpIcon,
  ArrowTrendingDownIcon,
  TrendingUpIcon,
  TrendingDownIcon,
  CurrencyDollarIcon,
  DollarSignIcon,
  CheckIcon,
  XIcon,
  XMarkIcon,
  UserIcon,
  CogIcon,
  Cog6ToothIcon,
  MenuIcon,
  Bars3Icon,
  ChevronRightIcon,
  ChevronDownIcon,
  StarIcon,
  HeartIcon,
  MailIcon,
  EnvelopeIcon,
  PhoneIcon,
  MapPinIcon,
  LocationMarkerIcon,
  ExclamationCircleIcon,
  InformationCircleIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  RefreshIcon,
  ArrowPathIcon,
  SearchIcon,
  MagnifyingGlassIcon,
  BellIcon,
  CalendarIcon,
  ClipboardListIcon,
  ClipboardDocumentListIcon,
  ClipboardCheckIcon_check,
  ClipboardDocumentCheckIcon,
  CreditCardIcon,
  WalletIcon,
  BanknotesIcon,
  GlobeAltIcon,
  ShieldCheckIcon,
  UserGroupIcon,
  ChartBarIcon,
  NoSymbolIcon,
  ThumbUpIcon,
  ThumbDownIcon,
  EyeIcon,
  EyeSlashIcon,
  LockClosedIcon,
  LockOpenIcon,
  KeyIcon,
  IdentificationIcon,
  DocumentTextIcon,
  FileText,
  FolderIcon,
  ArchiveIcon,
  TrashIcon,
  PencilIcon,
  PlusCircleIcon,
  MinusCircleIcon,
  XCircleIcon,
  CheckCircleIcon,
  CursorClickIcon,
  ExclamationTriangleIcon,
  ServerIcon,
  CloudUploadIcon,
  CloudDownloadIcon,
  CodeBracketIcon,
  TerminalIcon,
  CircleStackIcon,
  HelpCircle,
  DocumentIcon,
};

export {
  StarIcon as StarIconSolid,
  HeartIcon as HeartIconSolid,
  CheckCircleIcon as CheckCircleIconSolid,
  XCircleIcon as XCircleIconSolid,
} from '@heroicons/react/24/solid';
